url: "https://expressjs.com"
baseurl: "/"

# Site settings

defaults:
  -
    scope:
      path: "_posts" 
      type: "posts"
    values:
      layout: "post"
      menu: blog
      lang: en

# Build settings

plugins:
  - jekyll-redirect-from

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 math_engine: mathjax
 input: GFM
 hard_wrap: false
 syntax_highlighter: rouge

exclude: 
  - [uk/CHANGELOG.md]
  - vendor/bundle
  - node_modules/


github: [metadata]
